#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BleUtil.Resource", IsApplication=true)]

namespace BleUtil
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040006
			public const int bar_padding = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int button_font_size = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int default_font_size = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int default_padding = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int row_height = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int scan_button_height = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int scan_button_width = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int status_font_size = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int title_font_size = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int title_height = 2130968583;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int TextView01 = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int ble_disable_button = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int ble_enable_button = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int ble_nuke_button = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int ble_status = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int ble_unbond_all_button = 2131165186;
			
			// aapt resource value: 0x7f07000f
			public const int bond_button = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int connect_button = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int device_name = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int device_status = 2131165201;
			
			// aapt resource value: 0x7f07000e
			public const int disconnect_button = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int listView1 = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int native_ble_status = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int scan_for_x_sec_button = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int scan_for_x_sec_repeated_button = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int scan_infinite_button = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int scan_stop_button = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int textView2 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int unbond_button = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Ble_Button_Bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Ble_Status_Bar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Device_Entry = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int ble_disable = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int ble_enable = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int ble_native_status = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int ble_not_supported = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int ble_nuke = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int ble_options = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int ble_status = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int ble_unbond_all = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int device_bond = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int device_connect = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int device_disconnect = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int device_status = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int device_unbond = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int generic_ok = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int natively_not_scanning = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int natively_scanning = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int not_scanning = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int scan_for_x_sec = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int scan_for_x_sec_repeated = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int scan_infinite = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int scan_options = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int scan_status = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int scanning = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int stop_scanning = 2131034122;
			
			// aapt resource value: 0x7f05001a
			public const int uhoh_message_nuke = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int uhoh_message_nuke_cancel = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int uhoh_message_nuke_drop = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int uhoh_message_phone_restart = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int uhoh_message_phone_restart_ok = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int uhoh_message_weirdness = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int uhoh_message_weirdness_ok = 2131034144;
			
			// aapt resource value: 0x7f050019
			public const int uhoh_title = 2131034137;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int NoActionBar = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
